/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in installed projects. It is checked in so
// type-checking works from a clean clone once dependencies are installed.
