import Link from "next/link";
import { acceptDemoOfferAction } from "@/app/actions";
import { Screen, StateNotice } from "@/components/Screen";
import { opfinApi } from "@/lib/api/client";
import { getAccessToken } from "@/lib/auth/session";
import { formatUgx } from "@/lib/format";

export default async function LoanOfferPage({ searchParams }: { searchParams?: Promise<{ application?: string; error?: string; message?: string }> }) {
  const params = await searchParams;
  const token = await getAccessToken();
  const applicationId = Number(params?.application);
  const offer = applicationId
    ? await opfinApi.demoOffer(applicationId, token)
    : { data: { offer: (await opfinApi.demoDashboard(token)).data.latest_application?.demo_offer ?? null } };

  return (
    <Screen
      title="Loan offer"
      description="Mock investor-demo loan offer generated after affordability decisioning."
      action={<Link className="button" href="/loans/schedule">Review schedule</Link>}
    >
      <section className="panel">
        {params?.message ? <StateNotice state={params.error === "validation" ? "validation" : "server"} message={params.message} /> : null}
        {offer.data.offer ? (
          <>
            <h2>{offer.data.offer.status}</h2>
            <table className="table">
              <tbody>
                <tr><th>Principal</th><td>{formatUgx(offer.data.offer.principal_amount_minor)}</td></tr>
                <tr><th>Total repayment</th><td>{formatUgx(offer.data.offer.total_repayment_minor)}</td></tr>
                <tr><th>Duration</th><td>{offer.data.offer.duration_days} days</td></tr>
                <tr><th>Rate</th><td>{offer.data.offer.interest_rate}% {offer.data.offer.interest_type}</td></tr>
              </tbody>
            </table>
            {offer.data.offer.status === "pending_acceptance" ? (
              <form action={acceptDemoOfferAction}>
                <input type="hidden" name="offer_id" value={offer.data.offer.id} />
                <button className="button" type="submit">Accept offer</button>
              </form>
            ) : null}
            <StateNotice state="sandbox" message="Offer is generated by mock investor-demo decisioning." />
          </>
        ) : (
          <StateNotice state="empty" message="No offer is available. Submit an approved demo application first." />
        )}
      </section>
    </Screen>
  );
}
