import { DataTable } from "@/components/DataTable";
import { Screen, StateNotice } from "@/components/Screen";
import { OpfinApiError } from "@/lib/api/errors";
import { opfinApi } from "@/lib/api/client";
import { getAccessToken } from "@/lib/auth/session";
import { formatUgx } from "@/lib/format";

export default async function RepaymentSchedulePage() {
  const token = await getAccessToken();

  try {
    const dashboard = await opfinApi.demoDashboard(token);
    const activeLoan = dashboard.data.latest_application?.loan;

    if (!activeLoan) {
      return (
        <Screen title="Repayment schedule" description="Schedule view based on known loan schedule fields from the backend models.">
          <StateNotice state="empty" message="No active loan account is available for a repayment schedule." />
        </Screen>
      );
    }

    const schedule = activeLoan.schedules ?? (await opfinApi.repaymentSchedule()).data;

    return (
      <Screen title="Repayment schedule" description="Schedule view based on known loan schedule fields from the backend models.">
        <section className="panel">
          <StateNotice state="sandbox" message="Schedule is generated by the backend demo loan account flow; mock mode uses sandbox rows." />
          <DataTable
            rows={schedule}
            getKey={(row) => row.id}
            columns={[
              { label: "Due date", render: (row) => row.due_date },
              { label: "Principal", render: (row) => formatUgx(row.principal) },
              { label: "Interest", render: (row) => formatUgx(row.interest) },
              { label: "Outstanding", render: (row) => formatUgx(row.total_outstanding) }
            ]}
          />
        </section>
      </Screen>
    );
  } catch (error) {
    const state = error instanceof OpfinApiError ? error.kind : "server";
    const message = error instanceof Error ? error.message : "Unable to load repayment schedule.";

    return (
      <Screen title="Repayment schedule" description="Schedule view based on known loan schedule fields from the backend models.">
        <StateNotice state={state} message={message} />
      </Screen>
    );
  }
}
